version: '3.8'

services:
  # Tg bot
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: m-m-logistics-bot
    restart: always
    environment:
      - MONGO_URI=${MONGO_URL}
    env_file:
      - ./.env
    volumes:
      # Mount logs directory to host machine for persistent log storage
      - ./logs:/app/logs
    networks:
      - network

networks:
  network:
    driver: bridge